name: 'Release'

on:
  push:
    branches:
      - 'main'
      - 'DO-28'
  create:
    tags:
      - v*

permissions:
  id-token: write
  contents: read
  checks: write

env:
  IMAGE_NAME: public.ecr.aws/twisto/actions-techdocs

jobs:
  push_to_registry:
    name: Push image to ECR
    runs-on: [2core-4gb]
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # pin@v4.0.1
        with:
          role-to-assume: 'arn:aws:iam::${{ vars.AWS_CICD_ACCOUNT }}:role/ecr-cicd-github'
          aws-region: ${{ vars.AWS_CICD_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # pin@v2.0.1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{ sha }},enable=true
            type=raw,value=suffix=.latest

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
